### ISSUE TITLE
define two variables

### ISSUE THREAD

**Issue by dmarch** [markpayneatwork/RCMEMS#1]
Hi,
Excellent package! I am trying to download two variables from the same product using CMEMS.config(). Tried several options like:
variable = c("var1", "var2") OR using update()
None of them worked, but just found that this solution works:
variable = c("var1 --variable var2")

Example:
cfg <- CMEMS.config(python="python",
                    script="C:/motuclient-python/motuclient.py",
                    motu="http://nrt.cmems-du.eu/motu-web/Motu",
                    service.id = "MEDSEA_ANALYSIS_FORECAST_PHY_006_013-TDS",
                    product.id = "med-cmcc-cur-an-fc-d",
                    variable = "uo --variable vo")

Suggestion:
It would be great to be able to provide >1 variable using this format: variable = c("var1", "var2")

**Comment by markpayneatwork** [comment]
Thanks for the suggestion david - it is a good one, and I wasn't aware that it was possible to download multiple variables in this way - it should be easy to implement though. I'll let you know when I make the commit.

**Comment by markpayneatwork** [comment]
Implemented now in df7b91dc9cd5a485d8c01896d9b46aaf04f8fa7b (Version 1.0)
